### ISSUE TITLE
[qiskit-aer-gpu] ImportError: libcustatevec.so.1

### ISSUE THREAD

**Issue by derwind** [Qiskit/qiskit-aer#1874]
### Informations

- **Qiskit Aer version**: qiskit-aer-gpu 0.12.2
- **Python version**: 3.11
- **Operating system**: Ubuntu 22.04
- **CUDA version**: 12.1.1 / 11.8.0

### What is the current behavior?

If I run the following procedure in a very clean environment, I will get a library load error and not be able to use qiskit_aer.

```python
>>> import qiskit_aer
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
ImportError: libcustatevec.so.1: cannot open shared object file: No such file or directory

### Steps to reproduce the problem

1. Create a clean environment. For example, use the following docker images:

- [docker/python311-ubutnu22/cuda121](https://github.com/derwind/cuquantum_on_colab/tree/qiskit-aer-gpu-0.12.2-py311/qiskit-aer-gpu/docker/python311-ubutnu22/cuda121)
- [docker/python311-ubutnu22/cuda118](https://github.com/derwind/cuquantum_on_colab/tree/qiskit-aer-gpu-0.12.2-py311/qiskit-aer-gpu/docker/python311-ubutnu22/cuda118)

2. Enter a clean environment. e.g., `docker run -it --rm --gpus all python311:ubuntu22-cuda121` if you will use docker images above.

3. Set up `qiskit-aer-gpu` with the following steps

```sh
pip install qiskit
pip uninstall -y qiskit-aer
pip install "qiskit-aer-gpu==0.12.2"
```

(For CUDA 11.8 the last line would be `pip install "qiskit-aer-gpu-cu11==0.12.2"`.)

4. Run `python -c "import qiskit_aer"`

### What is the expected behavior?

Importing `qiskit_aer` will successfully finish.

### Suggested solutions

It would be nice if the library paths (`LD_LIBRARY_PATH`) could be properly set. One work around would be:

```sh
mkdir -p /usr/local/nvidia/lib64
ln -s /usr/local/lib/python3.11/site-packages/cuquantum/lib/libcustatevec.so.1 /usr/local/nvidia/lib64/libcustatevec.so.1
ln -s /usr/local/lib/python3.11/site-packages/cuquantum/lib/libcutensornet.so.2 /usr/local/nvidia/lib64/libcutensornet.so.2
ln -s /usr/local/lib/python3.11/site-packages/cutensor/lib/libcutensor.so.1 /usr/local/nvidia/lib64/libcutensor.so.1
```

**Comment by hhorii** [comment]
Now Aer uses cuquantum PiPy package and I'm wondering that this is an issue to use the package. 

https://github.com/Qiskit/qiskit-aer/blob/b4e393c57a946a5f003f9065c7887d1c4ff6f2dd/setup.py#L59

**Comment by Jookare** [comment]
Should the #1877 have fixed this one? Still facing the same issue when trying to use the qiskit-aer-gpu python package

**Comment by doichanj** [comment]
The problem is fixed and merged but qiskit-aer-gpu is not released on PyPI.
Please refer to #1882 and build from source until new qiskit-aer-gpu will be released.

**Comment by VuPNam** [comment]
> The problem is fixed and merged but qiskit-aer-gpu is not released on PyPI. Please refer to #1882 and build from source until new qiskit-aer-gpu will be released.

Hi, I have been able to build from source for the qiskit-aer-gpu as you mentioned in #1882 , and until the end of that notebook everything ran fine and I saw no problems. However, when I try to import AerSimulator to see if I can access the 'tensor_network' methods, I could not do so. I'll be grateful if you could help me with this.
![image](https://github.com/Qiskit/qiskit-aer/assets/109680854/2fc5259b-2f6b-4170-aedc-830559148eb7)

**Comment by doichanj** [comment]
Please try building with option `-DAER_PYTHON_CUDA_ROOT=/home/lghafourpour/.local`
This option sets the path to the local Python environments.

**Comment by doichanj** [comment]
I think this is a bug in GCC 11 https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100438
Please try using other version of compiler

**Comment by gluca99** [comment]
@doichanj  Thank you for all the help. Unfortunately, I was still unable to make the relevant fix. However, since my deadline for this project is due next Friday, I've been able to find ways around needing the GPU version. Out of curiosity, when is the fixed version of the library going to be released on PyPi?

**Comment by doichanj** [comment]
We are planning to include this fix in 0.13.0 release.
I created binary distribution of the latest codes and put on TestPyPI temporary. 
https://test.pypi.org/project/qiskit-aer-gpu/0.13.0/

Before installing by pip, other required packages should be installed manually, as following
`pip install nvidia-cuda-runtime-cu12 nvidia-cublas-cu12 nvidia-cusolver-cu12 nvidia-cusparse-cu12 cuquantum-cu12`

The example is here : https://colab.research.google.com/drive/1bXwlFyfoJmAw2nrMZDN8oYe8PAgqV8Co?usp=sharing

**Comment by derwind** [comment]
This is a validation report.

I tried to build `qiskit-aer` according to @doichanj 's https://colab.research.google.com/drive/1mLEYEPzBJTJmCDRjFJ9tHuacYu15c0hY?usp=sharing on my devenv in my GCP Compute Engine VM using a  CUDA 12-based docker image (included in my issue report).

## Summary

In short, **build process essentially successes** except a small problem (will be referred later). Of course we no longer need to set additional paths to `LD_LIBRARY_PATH`.

## Detail

```sh
$ docker run -it --rm --gpus all python311:ubuntu22-cuda121
# pip install qiskit-aer
# pip uninstall -y qiskit-aer
# git clone https://github.com/Qiskit/qiskit-aer
# pip install nvidia-cuda-runtime-cu12 nvidia-cublas-cu12 nvidia-cusolver-cu12 nvidia-cusparse-cu12 cuquantum-cu12
# pip install -r qiskit-aer/requirements-dev.txt
# pip install pybind11
```

and then

```sh
# cd qiskit-aer
# python ./setup.py bdist_wheel -- -DAER_THRUST_BACKEND=CUDA -DCMAKE_VERBOSE_MAKEFILE=true  -DAER_DEBUG=false -DAER_MPI=false -DCMAKE_CUDA_FLAGS=-std=c++14 -DAER_PYTHON_CUDA_ROOT=/usr/local  --
```

which will fail due to:

```sh
---
CMake Error at /usr/local/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
---
```

so we may need to do the following procedure in addition (if needed):

```sh
# apt update && apt install -y libopenblas-dev
```

I retried:

```sh
# cd qiskit-aer
# python ./setup.py bdist_wheel -- -DAER_THRUST_BACKEND=CUDA -DCMAKE_VERBOSE_MAKEFILE=true  -DAER_DEBUG=false -DAER_MPI=false -DCMAKE_CUDA_FLAGS=-std=c++14 -DAER_PYTHON_CUDA_ROOT=/usr/local  --
```

which successfully finished after several (about 5~10) minutes. So I installed `qiskit-aer` by

```sh
# pip install -U dist/*
```

Finally I tested with two (CPU and cuTensorNet) simulators of

```python
sim = AerSimulator(method='statevector')
```

and

```python
sim_gpu = AerSimulator(method='tensor_network', device='GPU')
```

and both are OK. I also tested with:

```python
sim_gpu_cusv = AerSimulator(method='statevector', device='GPU', cuStateVec_enable=True)
```

and this is also OK.

```python
>>> print(result_gpu_cusv.to_dict()['results'][0]['metadata']['cuStateVec_enable'])
True
```

**Comment by ironfrown** [comment]
I have found that the installation problem to do with "custatevec.h" is due to the missing cuQuantum and cuTensor. Once these two NVIDIA products are installed then all of the required components and headers can be found, and the qiskit-aer-gpu compiles fine (well, with lots and lots warnings). Perhaps, this needs to be added to qiskit-aer-gpu documentation as a requirement (it may be obvious for some but not for others).

**Comment by juggernaut545** [comment]
I am as well still encountering this issue. I recreate a conda environment and specifically pip installed the qiskit-aer-gpu-cu11 package, but the custatevec.h file is still missing. Has there been any update?

**Comment by doichanj** [comment]
Now the latest version of Aer is 0.13.1 but the latest GPU distribution is not published yet because of PyPI's new authorization. This problem should be fixed on the latest Aer

**Comment by juggernaut545** [comment]
Do you have any other advice as to how to fix the file missing error? I pip installed the qiskit-aer-gpu and installed the cuQuantum and cuTensor as the previous response said. However, I am still encountering this error. Could it perhaps be due to the cuda environment or something similar?

**Comment by doichanj** [comment]
I put GPU distributions of Aer 0.13.1 on release page, https://github.com/Qiskit/qiskit-aer/releases
Please download one for your environment instead of `pip install qiskit-aer-gpu`

**Comment by juggernaut545** [comment]
> I put GPU distributions of Aer 0.13.1 on release page, https://github.com/Qiskit/qiskit-aer/releases Please download one for your environment instead of `pip install qiskit-aer-gpu`

Thanks for the reply. I am locally installing it to the computer, and then doing pip install "filename.whl", but I believe the python versions might be incompatible as I am getting the "'filename.whl' is not a supported wheel on this platform". 
I am currently running python 3.12 and the latest version of the .whl file I see is 3.10. Does this mean that I have to change my python version, or is there a 3.12 version?

**Comment by edmondium** [comment]
> Now the latest version of Aer is 0.13.1 but the latest GPU distribution is not published yet because of PyPI's new authorization. This problem should be fixed on the latest Aer

i'm waiting for this solution.

**Comment by edmondium** [comment]
> ### Informations
> * **Qiskit Aer version**: qiskit-aer-gpu 0.12.2
> * **Python version**: 3.11
> * **Operating system**: Ubuntu 22.04
> * **CUDA version**: 12.1.1 / 11.8.0
> 
> ### What is the current behavior?
> If I run the following procedure in a very clean environment, I will get a library load error and not be able to use qiskit_aer.
> 
> ```python
> >>> import qiskit_aer
> ```
> 
> Traceback (most recent call last): File "", line 1, in ... ImportError: libcustatevec.so.1: cannot open shared object file: No such file or directory
> 
> ### Steps to reproduce the problem
> 1. Create a clean environment. For example, use the following docker images:
> 
> * [docker/python311-ubutnu22/cuda121](https://github.com/derwind/cuquantum_on_colab/tree/qiskit-aer-gpu-0.12.2-py311/qiskit-aer-gpu/docker/python311-ubutnu22/cuda121)
> * [docker/python311-ubutnu22/cuda118](https://github.com/derwind/cuquantum_on_colab/tree/qiskit-aer-gpu-0.12.2-py311/qiskit-aer-gpu/docker/python311-ubutnu22/cuda118)
> 
> 2. Enter a clean environment. e.g., `docker run -it --rm --gpus all python311:ubuntu22-cuda121` if you will use docker images above.
> 3. Set up `qiskit-aer-gpu` with the following steps
> 
> ```shell
> pip install qiskit
> pip uninstall -y qiskit-aer
> pip install "qiskit-aer-gpu==0.12.2"
> ```
> 
> (For CUDA 11.8 the last line would be `pip install "qiskit-aer-gpu-cu11==0.12.2"`.)
> 
> 4. Run `python -c "import qiskit_aer"`
> 
> ### What is the expected behavior?
> Importing `qiskit_aer` will successfully finish.
> 
> ### Suggested solutions
> It would be nice if the library paths (`LD_LIBRARY_PATH`) could be properly set. One work around would be:
> 
> ```shell
> mkdir -p /usr/local/nvidia/lib64
> ln -s /usr/local/lib/python3.11/site-packages/cuquantum/lib/libcustatevec.so.1 /usr/local/nvidia/lib64/libcustatevec.so.1
> ln -s /usr/local/lib/python3.11/site-packages/cuquantum/lib/libcutensornet.so.2 /usr/local/nvidia/lib64/libcutensornet.so.2
> ln -s /usr/local/lib/python3.11/site-packages/cutensor/lib/libcutensor.so.1 /usr/local/nvidia/lib64/libcutensor.so.1
> ```

in my case, the library is in here,
(quantum) edmondium@LAPTOP-1Q9H40K6:~$ l /home/edmondium/quantum/lib/python3.11/site-packages/cuquantum/lib/
libcustatevec.so.1*  libcutensornet.so.2*

**Comment by JMuff22** [comment]
In case anyone is looking for a potential solution I have one. Running on Rocky Linux 8.8 with Cuda 12.2 

This works 

```
pip install cuquantum-python
pip install nvidia-cusparse-cu12 nvidia-cublas-cu12 nvidia-cuda-runtime-cu12 custatevec_cu12
pip install qiskit-aer-gpu==0.14.0.1

ln -s /usr/local/lib/python3.9/site-packages/cuquantum/lib/libcustatevec.so.1 /usr/local/cuda/lib64/libcustatevec.so.1
ln -s /usr/local/lib/python3.9/site-packages/cuquantum/lib/libcutensornet.so.2 /usr/local/cuda/lib64/libcutensornet.so.2
ln -s /usr/local/lib/python3.9/site-packages/cutensor/lib/libcutensor.so.2 /usr/local/cuda/lib64/libcutensor.so.2
```

Additionally, some problems with symengine for example:

```
File "/usr/local/lib/python3.9/site-packages/symengine/__init__.py", line 12, in <module>     import symengine.lib.symengine_wrapper as wrapper ModuleNotFoundError: No module named 'symengine.lib.symengine_wrapper'
```
See https://github.com/symengine/symengine.py/issues/474 
Can be resolved by building it yourself 

```
dnf install -y cmake gmp-devel

git clone https://github.com/symengine/symengine.git
cd symengine
mkdir build && cd build
cmake ..
make
make install
cd /opt/

git clone https://github.com/symengine/symengine.py.git
cd symengine.py
git checkout v0.11.0
sed -i 's/-DSYMENGINE_INSTALL_PY_FILES=OFF/-DSYMENGINE_INSTALL_PY_FILES=ON/' setup.py
python setup.py install
cd /opt/
```
